"""Facade over the db submodules: `from app import db; db.get_product(...)` etc.
still works exactly as it did when this was one flat database.py file — this
is the one place that decides what's public, not a rewrite of every caller."""
from app.db.schema import (
    DEPOSIT_CREDITED,
    DEPOSIT_PENDING,
    DEPOSIT_REJECTED,
    RAIL_BINANCE_PAY,
    RAIL_BSC,
    STATUS_APPROVED,
    STATUS_CREATED,
    STATUS_PENDING,
    STATUS_REJECTED,
    STORE_MODE_AUTO,
    STORE_MODE_MANUAL,
    UNLIMITED_STOCK,
    close_pool,
    init_pool,
)
from app.db.products import (
    EDITABLE_FIELDS,
    add_product,
    add_product_keys,
    clear_expired_offers,
    clear_offer,
    clear_unused_keys,
    count_unused_keys,
    decrement_stock,
    delete_product,
    effective_price,
    effective_stock,
    get_effective_stock,
    get_key_pool_count,
    get_key_pool_counts,
    get_product,
    list_products,
    pop_unused_keys,
    set_product_active,
    set_product_offer,
    update_product,
)
from app.db.orders import (
    clear_abandoned_orders,
    clear_data,
    clear_successful_orders,
    count_user_orders,
    create_order,
    earnings_summary,
    get_order,
    list_abandoned_orders,
    list_orders,
    reject_order,
    set_order_method,
    set_order_status,
    set_order_utr,
    today_summary,
)
from app.db.users import all_recipient_ids, all_users, delete_users, get_user, record_user, set_user_notes
from app.db.wallet import (
    create_deposit,
    create_tagged_deposit,
    credit_deposit_once,
    credit_wallet,
    debit_wallet,
    delete_wallet_data_for_users,
    get_cursor,
    get_ledger,
    get_wallet_balance,
    is_tx_processed,
    list_unnotified_manual_credits,
    list_unnotified_rejections,
    mark_deposit_notified,
    pending_deposit_summary,
    set_cursor,
    today_deposit_summary,
)
from app.db.settings import get_store_mode, set_store_mode

__all__ = [
    "DEPOSIT_CREDITED", "DEPOSIT_PENDING", "DEPOSIT_REJECTED", "RAIL_BINANCE_PAY", "RAIL_BSC",
    "STATUS_APPROVED", "STATUS_CREATED", "STATUS_PENDING", "STATUS_REJECTED",
    "STORE_MODE_AUTO", "STORE_MODE_MANUAL",
    "UNLIMITED_STOCK", "close_pool", "init_pool",
    "EDITABLE_FIELDS", "add_product", "add_product_keys", "clear_expired_offers",
    "clear_offer", "clear_unused_keys", "count_unused_keys",
    "decrement_stock", "delete_product", "effective_price", "effective_stock",
    "get_effective_stock",
    "get_key_pool_count", "get_key_pool_counts", "get_product", "list_products",
    "pop_unused_keys", "set_product_active", "set_product_offer", "update_product",
    "clear_abandoned_orders", "clear_data", "clear_successful_orders",
    "count_user_orders",
    "create_order", "earnings_summary", "get_order", "list_abandoned_orders",
    "list_orders", "reject_order", "set_order_method", "set_order_status",
    "set_order_utr", "today_summary",
    "all_recipient_ids", "all_users", "delete_users", "get_user", "record_user", "set_user_notes",
    "create_deposit", "create_tagged_deposit", "credit_deposit_once", "credit_wallet",
    "debit_wallet", "delete_wallet_data_for_users", "get_cursor", "get_ledger",
    "get_wallet_balance", "is_tx_processed", "list_unnotified_manual_credits",
    "list_unnotified_rejections", "mark_deposit_notified", "pending_deposit_summary",
    "set_cursor", "today_deposit_summary",
    "get_store_mode", "set_store_mode",
]
